### ISSUE TITLE
[Tracker] js-libp2p getting full Type Script support

### ISSUE THREAD

**Issue by BigLep** [libp2p/js-libp2p#1021]
A few years ago we took the decision on TypeScript to not convert modules to the language, because it's not a standard, it's controlled by a single vendor, it requires lots of extra tooling and there were far more JavaScript developers than TypeScript developers, and all TypeScript developers could write JavaScript but the reverse was not always true.

We were going to use JSDoc comments to generate types so people could use libp2p/ipfs modules in typed environments.  TypeScript developers would get types, and JavaScript developers would get comments, everyone would be happy.

Fast forward a few years and what's changed?  TypeScript has gone from strength to strength, that single-vendor has made some significant plays in open source with acquisitions of npm and GitHub so they're not going anywhere.  Far more developers are writing TypeScript than before.

The JSDoc comment thing didn't work out - it's full of gotchas and introduces so much cruft to the codebase that it makes it unpalatable to both JavaScript developers and TypeScript developers - full TypeScript ends up being much less verbose.  We tried writing complex types in `.d.ts` files but the tooling isn't there to validate them, so we've ended up writing `.ts` anyway.

Meanwhile JavaScript has moved on, as it did from callbacks to promises, now it's away from CJS and towards ESM.

We've been shipping most new code in dual CJS/ESM mode which has meant we've been able to support future-tech like [skypack](https://www.skypack.dev) but also maintain compatibility with older tools that use the [resolve](https://www.npmjs.com/package/resolve) module from [browserify](https://browserify.org/) like [jest](https://jestjs.io/), this is also full of footguns, for example `instanceof` not working between instantiated from CJS then used with `instanceof` in ESM.

Many of our dependencies are now ESM only - since we bundle CJS and ESM we can't update to these as our CJS code would end up pulling in the ESM dependency via a `require` which isn't compatible.

Fast forward to now.  We're standing on the cusp of a CJS to ESM transition, so why not take the opportunity this presents to embrace the peace of mind TypeScript brings at the same time.

We will refactor existing libp2p modules from CJS to TypeScript which will be published as ESM only with export maps and all that good stuff.  This will let us move quickly and safely while supporting new tools and environments.

----

#### Porting

A cheat sheet for porting existing modules.  This will evolve over time as we move some of these steps into Aegir itself in order to reduce the amount of boilerplate required (testing/coding flow, I'm mostly looking at you).

* Re-use centralised ts config: https://github.com/libp2p/js-libp2p-utils/blob/chore/convert-to-typescript/tsconfig.json
* Build using tsc: https://github.com/libp2p/js-libp2p-utils/blob/f31fa9400a3f96cf3b1e0e112568bc72dba5ae9d/package.json#L49
* All src/tests in ts which means you have to build before running tests: https://github.com/libp2p/js-libp2p-utils/blob/f31fa9400a3f96cf3b1e0e112568bc72dba5ae9d/package.json#L40
* Specify test files under /dist to the test runner: https://github.com/libp2p/js-libp2p-utils/blob/f31fa9400a3f96cf3b1e0e112568bc72dba5ae9d/package.json#L41
* Output type is "module": https://github.com/libp2p/js-libp2p-utils/blob/f31fa9400a3f96cf3b1e0e112568bc72dba5ae9d/package.json#L6
* Public API defined in "exports": https://github.com/libp2p/js-libp2p-utils/blob/f31fa9400a3f96cf3b1e0e112568bc72dba5ae9d/package.json#L7-L26
* Types in "typesVersions": https://github.com/libp2p/js-libp2p-utils/blob/f31fa9400a3f96cf3b1e0e112568bc72dba5ae9d/package.json#L27-L34

----

#### PRs

- [x] https://github.com/libp2p/js-libp2p-interfaces/pull/111
- [x] https://github.com/libp2p/js-libp2p-utils/pull/20
- [x] https://github.com/libp2p/js-libp2p-tcp/pull/152
- [ ] https://github.com/ipfs-shipyard/varint-decoder/pull/4
- [x] https://github.com/alanshaw/it-pipe/pull/6
- [x] https://github.com/alanshaw/it-goodbye/pull/5
- [x] https://github.com/alanshaw/it-ws/pull/6
- [x] https://github.com/vasco-santos/is-loopback-addr/pull/41
- [x] https://github.com/alanshaw/it-pair/pull/5
- [x] https://github.com/alanshaw/get-iterator/pull/14
- [x] https://github.com/alanshaw/abortable-iterator/pull/16
- [x] https://github.com/alanshaw/it-pushable/pull/12
- [x] https://github.com/alanshaw/it-block/pull/5
- [x] https://github.com/alanshaw/it-reader/pull/7
- [x] https://github.com/alanshaw/it-length-prefixed/pull/18
- [x] https://github.com/jacobheun/it-handshake/pull/4
- [x] https://github.com/libp2p/js-libp2p-websockets/pull/140
- [x] https://github.com/libp2p/js-libp2p-webrtc-star/pull/401
- [x] https://github.com/libp2p/js-libp2p-mplex/pull/158
- [x] https://github.com/libp2p/js-libp2p-bootstrap/pull/119
- [x] https://github.com/libp2p/js-libp2p-mdns/pull/113
- [x] https://github.com/libp2p/js-libp2p-record/pull/32
- [x] https://github.com/libp2p/js-libp2p-floodsub/pull/139
- [x] https://github.com/libp2p/js-libp2p-kad-dht/pull/300
- [x] https://github.com/libp2p/js-libp2p-delegated-content-routing/pull/67
- [x] https://github.com/libp2p/js-libp2p-delegated-peer-routing/pull/58
- [x] https://github.com/libp2p/js-libp2p-bootstrap/pull/121
- [x] https://github.com/libp2p/js-libp2p-delegated-content-routing/pull/68
- [x] https://github.com/libp2p/js-libp2p-delegated-peer-routing/pull/59
- [x] https://github.com/libp2p/js-libp2p-floodsub/pull/140
- [x] https://github.com/libp2p/js-libp2p-kad-dht/pull/302
- [x] https://github.com/libp2p/js-libp2p-mdns/pull/116
- [x] https://github.com/libp2p/js-libp2p-mplex/pull/162
- [x] https://github.com/libp2p/js-libp2p-websockets/pull/146
- [x] https://github.com/libp2p/js-libp2p-tcp/pull/172
- [x] https://github.com/ChainSafe/js-libp2p-noise/pull/134
- [x] https://github.com/ChainSafe/js-libp2p-noise/pull/137
- [x] https://github.com/libp2p/interop/pull/58
- [x] https://github.com/libp2p/js-libp2p-daemon/pull/78
- [ ] https://github.com/ChainSafe/js-libp2p-gossipsub/pull/206/
- [x] https://github.com/libp2p/js-libp2p/pull/1172

Needed for examples:
- [x] https://github.com/libp2p/js-libp2p-webrtc-direct/pull/151
- [x] https://github.com/libp2p/js-libp2p-pubsub-peer-discovery/pull/12

**Comment by dapplion** [comment]
:heart_eyes:

**Comment by wemeetagain** [comment]
Not sure what the current scope of this issue is, but would be nice to include lower level dependencies in this, too.
eg: @achingbrain 's `it` monorepo and @alanshaw 's `it-*` packages, things like that.

This would also be an opportunity to tighten up the types (remove `any` types).

**Comment by wemeetagain** [comment]
Another angle worth tackling that may be revisited with better typescript tooling:
docs generation from types

**Comment by achingbrain** [comment]
@wemeetagain yes to generated docs! Further discussion here - https://github.com/ipfs/js-ipfs/issues/4021

**Comment by achingbrain** [comment]
@BigLep yes, that one can be closed

**Comment by dapplion** [comment]
Let's goo! Excuse my past self for some pushy comments while asking for this some months ago. Thank you so much to the whole team for the hard work. You've made a downstream dev really happy :pray: 

![bring-in-celebration-meme](https://user-images.githubusercontent.com/35266934/161436850-4c71b5e5-b394-4a09-b00a-647e6036dbdd.jpg)

**Comment by achingbrain** [comment]
This has shipped in `libp2p@0.37.0` 🍾
