### ISSUE TITLE
Add documentation on mechanisms for node monitoring and protection

### ISSUE THREAD

**Issue by BigLep** [libp2p/js-libp2p#1378]
# Done Criteria
1. There is an easily discoverable way for a js-libp2p node operator to find the monitoring options available to them
2. We have a document we can point js-libp2p operators to in defense of or response to various resource exhaustion attacks (DoS, eclipse).

## Why Important
1. These are concepts that are best thought about in advance to prevent successful attacks.
2. If there is an attack, especially in the heat of battle, every minute reducing response/mitigation times can be significant.  Having suggestions/steps prethought outside the fog of war will provide better suggestions in a quicker period of time.

# Background
1. js-libp2p has various mechanisms to protect a node against attacks.  We want to make sure users are aware of the mechanisms available to them and that they're thinking about this.
3. go-libp2p and rust-libp2p used libp2p/docs as the entry point: https://github.com/libp2p/docs/issues/153.  js-libp2p can follow the same.
4. These need to get publicly documented in an easily discoverable place.  

# To-do

- [X] Update docs for monitoring https://github.com/libp2p/js-libp2p/pull/1441
- [x] Update DoS mitigation page https://github.com/libp2p/docs/pull/205
- [x] address comments in https://github.com/libp2p/js-libp2p/pull/1421 that came in after merging. 
 These are partially covered in https://github.com/libp2p/js-libp2p/pull/1456.

**Comment by p-shahi** [comment]
This item is completed. Some more docs (doc/LIMITS.md) will be updated as a part of https://github.com/libp2p/js-libp2p/issues/1508 but not a reason to keep this open
