### ISSUE TITLE
B. 🥊 Decentralized Hole Punching

### ISSUE THREAD

**Issue by p-shahi** [libp2p/js-libp2p#1461]
**Why:**  P2P networks can have a combination of both public and private nodes. While private nodes can dial nodes on the public Internet, they are unreachable from the outside as they are behind a NAT or a firewall. We need a mechanism to dial them. A [previous DHT crawl found that almost 63%](https://github.com/libp2p/specs/blob/master/ROADMAP.md#-hole-punching-on-tcp-and-quic) of the network was undialable.

**Goal:** Implement Decentralized Hole Punching in js-libp2p and bring it to parity with the Go and Rust implementations.

- [ ] https://github.com/libp2p/js-libp2p/issues/1005
- [ ] https://github.com/libp2p/js-libp2p/issues/1029
- [ ] https://github.com/libp2p/js-libp2p/issues/1459
- [ ] https://github.com/libp2p/js-libp2p/issues/1460

**Comment by momack2** [comment]
can we clarify that this is for js-ipfs in the title please?

**Comment by p-shahi** [comment]
@momack2 Any reason to include js-ipfs specifically? This work is not progressing with it in mind. We will need it for Helia but I would still not include any project in the title since it's better to remain product agnostic

**Comment by momack2** [comment]
sorry - I think I meant "js-libp2p" - the reason is because each of these cards shows up with out the repo title in starmaps - so otherwise you have many "holepunching" milesotnes without knowing they are for different libp2p implementations

**Comment by SgtPooki** [comment]
@momack2 we could include the repo-name on milestone cards in starmap to help mitigate this problem?

**Comment by p-shahi** [comment]
Didn't see the replies above but I support adding the repo-name to the milestone cards

**Comment by momack2** [comment]
Yeah, I think that would help a lot

**Comment by SgtPooki** [comment]
<details>
<summary>JS Colo 2024 discussion</summary>

We don't do hole-punching in TCP, hole-punching is much more successful with UDP (timing is more reliable)

TCP: ~30% success
UDP: ~70% success

</details>


### Things left to do:

1. Incorporate [QUIC transport](https://github.com/libp2p/js-libp2p/issues/1459)
2. Implement missing parts of DCUtR (the half after unilateral connection upgrade)

**Comment by jost-s** [comment]
@SgtPooki How is that statement about hole-punching success rate reconciled with [this statement in QUIC issue](https://github.com/libp2p/js-libp2p/issues/1459#issuecomment-2375343207), that QUIC does not have a higher success rate than TCP?
