### ISSUE TITLE
Circuit Relay v2 follow up work items

### ISSUE THREAD

**Issue by p-shahi** [libp2p/js-libp2p#1608]
I am going to merge this which will publish an RC to unblock other efforts as it is functional though it still needs some work in a follow-up before being released.

_Originally posted by @achingbrain in https://github.com/libp2p/js-libp2p/pull/1533#pullrequestreview-1322333583_

```[tasklist]
### Tasks
- [x] Split the code into two parts - the transport and the relay server
- [x] Configure the transport and relay server separately - at the moment the server is partially configured under the `config.relay.hop` key and `config.relay.advertise` - the fact that the docs say "Does not make you a relay" in several places mean it's really not obvious
- [x] Maybe even have a separate CircuitRelay transport that you can configure
- [x] More tests
```
