### ISSUE TITLE
Introduce smart dialing in js-libp2p

### ISSUE THREAD

**Issue by p-shahi** [libp2p/js-libp2p#2010]
## Goal

Reduce the number of outbound spurious dials that result in failed connections. This is especially a problem when dialing WebTransport addresses in Chromium where we often hit the 64 session limit https://github.com/libp2p/js-libp2p/issues/1896

Ref: notes on smart dialing in go-libp2p https://github.com/libp2p/go-libp2p/releases/tag/v0.29.0
```[tasklist]
### Tasks
- [x] fix(libp2p): only dial one address at a time for peers #2028
- [x] fix(libp2p): sort addresses to dial as public, then relay #2031
- [x] Increase no-redial threshold in browsers to greater than the WebTransport error timeout (fixed in #2028)
- [ ] https://github.com/libp2p/js-libp2p/pull/2033
- [ ] https://github.com/libp2p/js-libp2p/issues/2114
- [ ] https://github.com/libp2p/js-libp2p/issues/2150
```

**Comment by maschad** [comment]
It would be good to dog-feed this in https://github.com/libp2p/universal-connectivity to see how effective our dialling is after this refactor

**Comment by dhuseby** [comment]
Done!
