### ISSUE TITLE
release js-libp2p v1

### ISSUE THREAD

**Issue by SgtPooki** [libp2p/js-libp2p#2104]
discussed in https://pl-strflt.notion.site/Js-libp2p-v1-0-19d1a9724167469badaad4bf736cd7d6?pvs=4

```[tasklist]
### Tasks
- [ ] https://github.com/libp2p/js-libp2p/pull/2144
- [ ] https://github.com/libp2p/blog/issues/115
- [ ] https://github.com/libp2p/js-libp2p/pull/2107
- [ ] https://github.com/libp2p/js-libp2p/pull/2084
- [ ] https://github.com/libp2p/js-libp2p/issues/1913
- [ ] https://github.com/multiformats/js-multiformats/issues/249
- [ ] https://github.com/libp2p/js-libp2p/pull/2143
- [ ] Additional metadata/context on why multiaddrs are being listened on
```

### For blog post: 
- Why now
- Reminder of what all is in js-libp2p
- Significant accomplishments over the last year
    - New connectivity
    - Transports
    - Monorepo
    - Cherry pick things from the release notes

**Comment by achingbrain** [comment]
I'd like to get the WebRTC stream fixes released before doing this, but @maschad can get started on the blog post before then.

I've added some PRs that will target v1 to the task list above.

**Comment by achingbrain** [comment]
I have created a release-v1.0 branch that we can use to aggregate breaking changes ahead of release while not blocking bug fixes for `0.46.x`.

On merge day I will rebase this on top of master and push locally to preserve individual PR commits.

**Comment by achingbrain** [comment]
I have created a release-v1.0 branch that we can use to aggregate breaking changes ahead of release while not blocking bug fixes for `0.46.x`.

On merge day I will rebase this on top of master and push locally to preserve individual PR commits.

cc @maschad @wemeetagain

**Comment by achingbrain** [comment]
This has shipped!
