### ISSUE TITLE
Tracking - WebTransport browser bugs

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p#2572]
A list of browser bugs that block use of WebTransport.

# Chrome/Chromium

- [ ] https://issues.chromium.org/issues/40069954
- [ ] https://issues.chromium.org/issues/326887753

# Firefox

- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1806693
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1851679
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1872496
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1873263
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1899812

# Safari/WebKit

There is no support in currently shipping versions, though implementation work is in progress.

- https://github.com/WebKit/standards-positions/issues/18#issuecomment-1495890122
- [x] https://github.com/WebKit/WebKit/pull/17320

# Edge

WebTransport has been implemented and shipped.  Needs to be verified that it works as expected.

**Comment by sfroment** [comment]
Another issue that should be monitor is probably this one https://bugzilla.mozilla.org/show_bug.cgi?id=1659672 even though I'm not 100% sure it is what is blocking e2e test on firefox

**Comment by 2color** [comment]
It seems that the two Firefox bugs that are still open here have been closed;

- https://bugzilla.mozilla.org/show_bug.cgi?id=1899812
- https://bugzilla.mozilla.org/show_bug.cgi?id=1934402

@achingbrain Does this mean that WebTransport on Firefox is working well?

**Comment by achingbrain** [comment]
@2color no, there's another one 🙄  - https://bugzilla.mozilla.org/show_bug.cgi?id=1986138
