### ISSUE TITLE
Tracking Issue - WebRTC direct in Node.js

### ISSUE THREAD

**Issue by 2color** [libp2p/js-libp2p#2581]
## Background

[WebRTC-direct](https://github.com/libp2p/specs/blob/master/webrtc/webrtc-direct.md) is currently only supported in browsers [as mentioned in package](https://github.com/libp2p/js-libp2p/tree/main/packages/transport-webrtc#support). 

This is a tracking issue for adding support for WebRTC-direct in Node.js, which would allow browsers to dial Node.js directly (without circuit relay and signalling) without needing for a TLS certificate as in the case of WebSockets. 

## Dependencies 

This require changes to both https://github.com/murat-dogan/node-datachannel and https://github.com/paullouisageneau/libdatachannel to allow SDP Munging.

Related PRs/issues: 

```[tasklist]
### Tasks
- [ ] https://github.com/paullouisageneau/libjuice/pull/243
- [ ] https://github.com/paullouisageneau/libdatachannel/pull/1172
- [ ] https://github.com/paullouisageneau/libdatachannel/pull/1201
- [ ] https://github.com/paullouisageneau/libdatachannel/pull/1204
- [ ] https://github.com/murat-dogan/node-datachannel/pull/257
- [ ] https://github.com/murat-dogan/node-datachannel/pull/256
- [ ] https://github.com/libp2p/go-libp2p/issues/2827
```

**Comment by achingbrain** [comment]
There is good news when all of the above PRs are applied:

<img width="569" alt="image" src="https://github.com/libp2p/js-libp2p/assets/665810/0f2daded-1782-48e0-b9fd-7d2c5df0a895">

**Comment by christroutner** [comment]
I am trying to use webRTC in an exclusive node.js environment (no browser nodes). I created issue #2702 and wanted to link to it here, as it might be relevant to this discussion.

**Comment by achingbrain** [comment]
Closed by #2583
