### ISSUE TITLE
Tracking - WebRTC browser bugs

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p#2592]
A list of browser bugs that block use of WebRTC.

# Chrome/Chromium

- [x] https://issues.chromium.org/issues/40072842
- [ ] https://issues.chromium.org/issues/41378764

# Firefox

- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1902850

# Safari/WebKit

None

# Edge

None

**Comment by dozyio** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1988096 is fixed in nightly
