### ISSUE TITLE
libp2p@2.x.x release issue

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p#2626]
This is a list of breaking changes that will be released together as `libp2p@2.0.0`

The timescale is a little vague - likely Q3 2024 or sooner if PRs are ready eariler.

- [x] https://github.com/libp2p/js-libp2p/pull/2645
- [x] https://github.com/libp2p/js-libp2p/pull/2639
- [x] https://github.com/libp2p/js-libp2p/pull/2304
- [x] https://github.com/libp2p/js-libp2p/pull/2655
- [x] https://github.com/libp2p/js-libp2p/pull/2656
- [x] https://github.com/libp2p/js-libp2p/pull/2658
- [x] https://github.com/libp2p/js-libp2p/pull/2660
- [x] https://github.com/libp2p/js-libp2p/pull/2662
- [x] https://github.com/ipfs/js-stores/pull/315
- [x] https://github.com/ipfs/protons/pull/140
- [x] https://github.com/alanshaw/it-length-prefixed/pull/129
- [x] https://github.com/achingbrain/race-signal/pull/59
- [x] https://github.com/achingbrain/it/pull/140
- [x] https://github.com/ChainSafe/js-libp2p-gossipsub/pull/499
- [x] https://github.com/ChainSafe/js-libp2p-gossipsub/pull/500
- [x] https://github.com/ChainSafe/js-libp2p-noise/pull/440

Post release:

- [x] https://github.com/ChainSafe/js-libp2p-noise/pull/444
- [x] https://github.com/ChainSafe/js-libp2p-gossipsub/pull/504
- [x] https://github.com/libp2p/js-libp2p-daemon/pull/273
- [x] https://github.com/libp2p/interop/pull/159
- [x] https://github.com/libp2p/js-libp2p/pull/2694
- [x] https://github.com/libp2p/js-libp2p-pubsub-peer-discovery/pull/146
- [x] https://github.com/ipfs/js-ipns/pull/322
- [x] https://github.com/ipfs/js-kubo-rpc-client/pull/241
- [x] https://github.com/ipfs/js-ipfsd-ctl/pull/846
- [x] https://github.com/libp2p/js-libp2p-examples/pull/170
- [x] https://github.com/libp2p/js-libp2p/pull/2752

**Comment by achingbrain** [comment]
Closing as all tasks are complete!
