### ISSUE TITLE
epic: expose transport metrics

### ISSUE THREAD

**Issue by SgtPooki** [libp2p/js-libp2p#2664]
## Done Criteria

Export metrics leveraging the work done in https://github.com/libp2p/js-libp2p/issues/1458

## Motivation

Epic created since we only had one tracking the work from https://github.com/libp2p/js-libp2p/issues/1915

Better observability for performance and benchmarking. See: https://github.com/libp2p/js-libp2p/issues/1458#issuecomment-1323833476

## Related

* https://github.com/libp2p/js-libp2p/issues/1915
* https://github.com/libp2p/js-libp2p/pull/2649#discussion_r1716665370

```[tasklist]
### Tasks
- [ ] https://github.com/libp2p/js-libp2p/issues/1915
- [ ] feat: expose metrics for WebTransport
- [ ] feat: expose metrics for WebRTC
- [ ] feat: expose metrics for maconn upgrades in @libp2p/upgrader (part of `libp2p` npm package: https://github.com/libp2p/js-libp2p/blob/7939dbd5cbab1c7b4be671ff976d0258e9b48178/packages/libp2p/src/upgrader.ts#L126C36-L126C52)
```

**Comment by Nkovaturient** [comment]
Hey @SgtPooki , 
is the work on exposing metrics for WebRTC open? 
If so, can I proceed to explore and try to implement it?
im closely following WebSockets metrics to understand the code standards and derive insightful info as discussed here https://github.com/libp2p/js-libp2p/pull/2649 
Thank you!

**Comment by SgtPooki** [comment]
@Nkovaturient I am no longer helping maintain this repo, you might want to check with current maintainers
