### ISSUE TITLE
multiaddr string representation: use /p2p by default

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#386]
Support for `/p2p` in multiaddr has existed since December 17 of last year. It's time to migrate switch to using it by default. Currently we use `/ipfs` to indicate peer id's in a multiaddr and it is the default, but `/p2p` is preferred. In the greater effort to migrate completely away from `/ipfs`, this task is here to track the roll out of **only** switching the default.

## Breaking Changes
Older JS nodes who are not using the latest `multiaddr@6.x.x` release line, will not be able to understand the `/p2p` string representation. This shouldn't affect peers over the wire, but any string usage will cause issues.

Anyone using js-libp2p older than 0.25 **may** be affected. You can run `npm ls multiaddr` to check that you have version of `multiaddr >= 6.0.2`. Older versions of multiaddr will likely have issues with the string representation of `/p2p`.

### js-ipfs
Anyone using js-ipfs@0.34 or later will be unaffected by this change, as it includes the `/p2p` codec.

## TODOs

- [x] Update [multiaddr](https://github.com/multiformats/js-multiaddr) to prioritize `/p2p` in a major version release
- [ ] Update the multiaddr version in a minor release for js-libp2p
- [ ] Update js-ipfs to use the new js-libp2p version, in a minor release

## Announcement

This is to track announcing the breaking change for older versions. Once a release date has been determined.

**Libp2p Release Version**: TBD

- [ ] [discuss.libp2p.io](https://discuss.libp2p.io)
- [ ] [discuss.ipfs.io](https://discuss.ipfs.io)
- [ ] Libp2p IRC
- [ ] Twitter
- [ ] Reddit

Parent issue: https://github.com/libp2p/libp2p/issues/79

**Comment by wemeetagain** [comment]
This is done
