### ISSUE TITLE
Awesome Endeavour: Examples with tests running in js-libp2p CI

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#571]
# Examples with tests running in js-libp2p CI

- **Version**: N/A
- **Platform**: N/A
- **Subsystem**: N/A

## What

Create tests for each of the `js-libp2p` examples.

## Why

Running tests for examples aims to ease and make our release process more efficient. In our current setup, every time we want to do a release, we need to manually guarantee that all the examples are running properly. Other than this being a time consuming task, it is prone to human error as there is no visual proof of things being working fine.

This effort time will be payed out by making the release process smoother and faster to validate.

## Task

There are several `js-libp2p` examples, across different running environments. It is worth dividing the examples in node examples and browser examples, since node examples are easier and faster to test, compared to the browser ones.

For each of the examples, we need to create tests that validate the correct behavior of each example, as well as add a CI job to run those tests.

### Node

- [ ] chat
- [ ] delegated-routing
- [ ] discovery-mechanisms
- [ ] echo
- [ ] encrypted-communications
- [ ] nat-traversal
- [ ] peer-and-content-routing
- [ ] pnet
- [ ] protocol-and-stream-muxing
- [ ] pubsub
- [ ] transports

### Browser

- [ ] libp2p-in-the-browser

**Comment by wemeetagain** [comment]
We have the examples/ repo now
