### ISSUE TITLE
[Meta] Crypto updates

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#615]
This is a meta issue to track work I will be doing around various crypto updates in libp2p.

## Noise
We are planning on deprecating `libp2p-secio` in favor of [`libp2p-noise`](https://github.com/NodeFactoryIo/js-libp2p-noise). ETA's are based on current estimated timelines of IPFS version updates and are subject to change.
 
- [x] js-libp2p uses `libp2p-noise` in all tests
- [x] js-libp2p uses `libp2p-noise` in all examples
- [x]  Integrate [`libp2p-noise` into js-ipfs](https://github.com/ipfs/js-ipfs/pull/3004) as fallback for `libp2p-secio` (ETA: June 23rd)
    - [ ] Remove support for `libp2p-secio` in js-ipfs (ETA: Aug 11th)

## ed25519 Keys (ETA: js-libp2p@0.29)
- [ ] js-libp2p defaults to ed25519 keys in all tests
- [x] libp2p/interop tests are being done on ed25519 keys
- [x] ipfs/interop tests are being done on ed25519 keys
- [x] ed25519 keys in `libp2p-crypto` match the API of rsa keys (they currently differ)
  - [x] Shoud fix https://github.com/ipfs/js-ipfs/issues/2553

## Big Fixes
- [ ] Resolve [MAC Invalid error](https://github.com/libp2p/js-libp2p/issues/310)
- [x] Interop ed25519 key marshaling https://github.com/libp2p/js-libp2p-crypto/issues/175

**Comment by jacobheun** [comment]
cc @achingbrain @hugomrdias @vasco-santos

**Comment by vasco-santos** [comment]
@jacobheun we should default [PeerId.create](https://github.com/libp2p/js-peer-id#createopts) to use `ed25519` keys as well. When would be a good time for that in this timeline?

**Comment by jacobheun** [comment]
> @jacobheun we should default PeerId.create to use ed25519 keys as well. When would be a good time for that in this timeline?

@vasco-santos we could time a breaking change of PeerId with the 0.29 work so that we time that with signed peer records.

**Comment by jacobheun** [comment]
The major outstanding issue left for this is Keychain support for ed25519 keys, which is due to a lack of [import/export support](https://github.com/libp2p/js-libp2p-crypto/issues/145) in js-libp2p-crypto.

**Comment by wemeetagain** [comment]
I believe all outstanding items have been implemented. Feel free to reopen if not the case
