### ISSUE TITLE
⚡️ 0.29 RELEASE 🚀

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#654]
> Libp2p hardening and improved browser experience

# 🗺 What's left for release

- [x] [libp2p/js-libp2p#653](https://github.com/libp2p/js-libp2p/issues/653)
- [x] [libp2p/js-libp2p#652](https://github.com/libp2p/js-libp2p/issues/652)

# 🔦 Highlights

## 🔒Signed Peer Records

A libp2p node shares its data publicly (e.g through the DHT) or relies on potentially untrustworthy intermediaries to relay information. This might have consequences as the peer data can be tempered by a third party.

A Signed Peer Record is an all-purpose data container that includes a signature of the data, so we can verify that the data came from a specific peer and that it hasn't been tampered with.

Signed peer records are now exchanged in the identify protocol and in gossipsub peer exchange (introduced in gossipsub 1.1).

## 🛡️Gossipsub v1.1

The [`libp2p-gossipsub`](https://github.com/ChainSafe/js-libp2p-gossipsub) javascript implementation is now upgraded according to the Gossipsub v1.1 [spec](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md) and it packs several security hardening extensions, thanks to ChainSafe ❤️ . You can read more about it in its release [blogpost](https://blog.ipfs.io/2020-05-20-gossipsub-v1.1/).

We leveraged this update to rethink the pubsub interface, in order to make it easier and straightforward, as well as to be consistent with the API of the routers. Moreover, the interface was also reconstructed to ease new pubsub router implementations. This means less code in the libp2p bundle, as well as less code to maintain and test.

## Uint8array replace Buffer

Aiming to improve libp2p browser support, we are moving away from node core modules unless we can guarantee that the code we are writing will not run in a browser. It is worth mentioning that modern JavaScript runtimes have TypedArrays such as Uint8Array backed by ArrayBuffers. All libp2p dependencies were also updated to use Uint8Array.

Part of the larger endeavour in https://github.com/ipfs/js-ipfs/issues/3220

# 🏗 API Changes

The pubsub API is being updated to be consistent with the new [js-libp2p-interfaces/src/pubsub](https://github.com/libp2p/js-libp2p-interfaces/tree/master/src/pubsub).

All the API parameters and return values that used `Buffer` are now using `Uint8array`.

You can check the full details about these changes in the [Migrating to libp2p@0.29](https://github.com/libp2p/js-libp2p/blob/master/doc/migrations/v0.28-v0.29.md) doc.

# ✅ Release Checklist

- Robustness and quality
  - [x] Ensure that all tests are passing, this includes:
    - [x] unit
  - [x] Publish a release candidate to npm
    ```sh
    # Minor prerelease (e.g. 0.24.1 -> 0.25.0-rc.0)
    $ npx aegir release --type preminor -t node -t browser --preid rc --dist-tag next

    # Increment prerelease (e.g. 0.25.0-rc.0 -> 0.25.0-rc.1)
    $ npx aegir release --type prerelease -t node -t browser --preid rc --dist-tag next
    ```
  - [x] Run tests of the following projects with the new release:
    - [x] [js-ipfs](https://github.com/ipfs/js-ipfs)
- Documentation
  - [x] Ensure that README.md is up to date
  - [x] Ensure that all the examples run
  - [x] Ensure that [libp2p/docs](https://github.com/libp2p/docs) is updated
- Communication
  - [x] Create the release issue
  - [x] Take a snapshot between of everyone that has contributed to this release (including its subdeps in IPFS, libp2p, IPLD and multiformats) using [`name-your-contributors`](https://www.npmjs.com/package/name-your-contributors). Generate a nice markdown list with [this script](https://gist.github.com/jacobheun/d2ff479ca991733c13cdcf688a1317e5)
  - [ ] Announcements (both pre-release and post-release)
    - [ ] Twitter
    - [ ] IRC
    - [ ] Reddit
    - [ ] [discuss.libp2p.io](https://discuss.libp2p.io/c/news)
  - [ ] Blog post
  - [x] Copy release notes to the [GitHub Release description](https://github.com/libp2p/js-libp2p/releases)

# ❤️ Huge thank you to everyone that made this release possible

In alphabetical order, here are all the humans that contributed to the release:

* [Aarnav](https://github.com/R9295) (2 issues, 1 comment)
* [Adam Uhlíř](https://github.com/AuHau) (1 PR, 2 issues, 5 comments)
* [Alan Shaw](https://github.com/alanshaw) (1 PR, 1 issue)
* [Alex Potsides](https://github.com/achingbrain) (45 PRs, 1 issue, 22 reviews, 27 comments)
* [anders](https://github.com/tabcat) (1 PR, 1 issue, 3 comments)
* [Belma Gutlic](https://github.com/morrigan) (8 reviews)
* [Bernd Strehl](https://github.com/Strernd) (2 PRs, 1 issue, 6 comments)
* [Cayman](https://github.com/wemeetagain) (32 PRs, 9 issues, 46 reviews, 18 comments)
* [Danny Thorpe](https://github.com/dthorpe) (1 PR, 2 issues, 2 reviews)
* [David Dahl](https://github.com/daviddahl) (1 comment)
* [Dietrich Ayala](https://github.com/autonome) (4 comments)
* [Fabián Heredia Montiel](https://github.com/fabianhjr) (1 comment)
* [Felipe Martins](https://github.com/felipemarts) (1 PR, 2 comments)
* [Francis Gulotta](https://github.com/reconbot) (1 PR)
* [Geolffrey Mena](https://github.com/geolffreym) (4 PRs, 3 issues, 8 comments)
* [Gregory Markou](https://github.com/GregTheGreek) (2 comments)
* [Haad](https://github.com/haadcode) (1 PR, 1 comment)
* [Hubertus Hohl](https://github.com/ffa500) (1 PR, 2 issues, 2 comments)
* [Hugo Dias](https://github.com/hugomrdias) (5 PRs, 7 reviews, 10 comments)
* [Irakli Gozalishvili](https://github.com/Gozala) (5 PRs, 9 reviews, 27 comments)
* [jacekv](https://github.com/jacekv) (1 issue, 1 comment)
* [Jacob Heun](https://github.com/jacobheun) (25 PRs, 8 issues, 96 reviews, 100 comments)
* [Joel Thorstensson](https://github.com/oed) (2 issues, 2 comments)
* [Jose Aguinaga](https://github.com/jjperezaguinaga) (2 PRs, 2 issues, 7 comments)
* [Josh Field](https://github.com/HexaField) (1 issue)
* [Lion - dapplion](https://github.com/dapplion) (1 PR)
* [Marcin Rataj](https://github.com/lidel) (1 review, 1 comment)
* [Marco Ippolito](https://github.com/marcoippolito) (2 issues, 4 comments)
* [Marin Petrunić](https://github.com/mpetrunic) (6 PRs, 11 reviews, 16 comments)
* [Mikeal Rogers](https://github.com/mikeal) (1 comment)
* [Moody Salem](https://github.com/moodysalem) (1 issue, 5 comments)
* [olivier](https://github.com/olivier-nerot) (4 issues, 5 comments)
* [Orie Steele](https://github.com/OR13) (1 issue)
* [Peter Rabbitson](https://github.com/ribasushi) (1 review)
* [phillmac](https://github.com/phillmac) (2 issues, 2 comments)
* [planetoryd](https://github.com/planetoryd) (1 issue)
* [Rod Vagg](https://github.com/rvagg) (4 reviews, 3 comments)
* [sahilpohare](https://github.com/sahilpohare) (1 review)
* [stale](undefined) (6 comments)
* [Steven Allen](https://github.com/Stebalien) (1 issue, 2 comments)
* [straiforos](https://github.com/straiforos) (1 comment)
* [Vasco Santos](https://github.com/vasco-santos) (46 PRs, 9 issues, 161 reviews, 113 comments)
* [Vojtech Simetka](https://github.com/vojtechsimetka) (1 PR)
* [Volker Mische](https://github.com/vmx) (16 reviews, 1 comment)
* [Xplorer123](https://github.com/Xplorer123) (1 issue)
* [Zé Bateira](https://github.com/zebateira) (1 PR)

# 🙌🏽 Want to contribute?

Would you like to contribute to the libp2p project and don't know how? Well, there are a few places you can get started:

- Check the issues with the `help wanted` label in the [libp2p repo](https://github.com/libp2p/js-libp2p/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)
- Join an IPFS All Hands, introduce yourself and let us know where you would like to contribute - https://github.com/ipfs/team-mgmt#all-hands-call
- Hack with IPFS and show us what you made! The All Hands call is also the perfect venue for demos, join in and show us what you built
- Join the discussion at http://discuss.libp2p.io/ and help users finding their answers.
- Join the [⚡️libp2p Weekly Sync 🙌🏽](https://github.com/libp2p/team-mgmt/issues/16) and be part of the Sprint action!

# ⁉️ Do you have questions?

The best place to ask your questions about libp2p, how it works and what you can do with it is at [discuss.libp2p.io](https://discuss.libp2p.io). We are also available at the #libp2p channel on Freenode.

**Comment by jacobheun** [comment]
Per discussions over at https://github.com/ipfs/go-ipfs/issues/7433#issuecomment-656410330, we should look at getting some better built in support for AutoRelay or an AutoRelay like component. I'll create an issue for tracking the specific use case and how we can look at phasing in improved support for this. I think there are some quicker changes we could potentially land in 0.29, and then we can phase in more in subsequent releases.

**Comment by negamaxi** [comment]
It seems like this release was already published 20 days ago...

https://github.com/libp2p/js-libp2p/releases/tag/v0.29.0

**Comment by jacobheun** [comment]
Yes it was, I'll switch the pinned issues to 0.30.
