### ISSUE TITLE
⚡️ 0.30 RELEASE 🚀

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#655]
> Libp2p is becoming self sufficient on discoverability and connectivity - The first step

# 🔦 Highlights

## 📝 Type definitions

`js-libp2p` is now distributed with type definitions for TypeScript in its core API. We are using JSDoc to type the code inline and [aegir](https://github.com/ipfs/aegir) for type checking and generate type definitions on release.

Upstream typescript projects have been leveraging projects like https://github.com/ChainSafe/libp2p-ts to have definitions for libp2p. With `0.30` typescript projects can start using the built in libp2p types.

This will also enable us to provide automated (and updated) docs, without the need to manually keep them.

## 🌐 Auto relay

AutoRelay enables libp2p nodes to dynamically find and bind to relays on the network. Once binding (listening) is done, the node can and should advertise its addresses to the network, allowing any other node to dial it over its bound relay(s). While direct connections to nodes are preferable, it's not always possible to do so due to NATs or browser limitations.

This is a crucial feature in terms of connectivity for some peers in the network, which will now be able to connect to other peers in a more independent fashion.

## 🗺 Improved Peer advertising and Dialer mechanics

Libp2p announces all the addresses a peer is listening on. However, most of the time these addresses include local private addresses, which as expected are not reachable. With peer store persistence, other peers will store (and even exchange) these local private addresses that will not be useful for others. Libp2p now supports a `customAnnounceFilter` function that enables via config to not announce any private addresses for instance. For simplifying this even more, `libp2p-utils` already has some filters that can just be imported and used.

`libp2p-websockets` has allowed TCP and DNS addresses, both with ws or wss, to be used for dialling. This should not be the default scenario due to security and browser policies. Now, `libp2p-websockets` will only support DNS based multiaddrs, as well as supporting `wss` only in the browser. And yes, you still need other types of multiaddrs for testing/development and we got you covered. You can override the websockets filter config easily via transport config options.

On more general dialer mechanics enhancements, the dialer will now sort the known addresses of a peer on a public and certified first logic. This way, the dialer will try to dial first the addresses that in theory will be more likely to work. This behaviour can also be configured via a custom function in the config.

Last but not least, in order for other nodes on the network to easily find a given libp2p node, this node will now recurrently find its closest peers on the network, connect to them and exchange its address records. This will enable other peers on the network to find a peer in an easier and faster fashion.

## 📂 Production Guides and Examples improvements

Taking into account the importante of the Auto relay, this release also comes with comprehensive examples and production guides on how the needed infrastructure blocks should be setup.

# 🏗 API Changes

https://github.com/libp2p/js-libp2p/blob/master/doc/migrations/v0.29-v0.30.md

# ✅ Release Checklist

- Robustness and quality
  - [x] Ensure that all tests are passing, this includes:
    - [x] unit
  - [x] Publish a release candidate to npm
    ```sh
    # Minor prerelease (e.g. 0.24.1 -> 0.25.0-rc.0)
    $ npx aegir release --type preminor -t node -t browser --preid rc --dist-tag next

    # Increment prerelease (e.g. 0.25.0-rc.0 -> 0.25.0-rc.1)
    $ npx aegir release --type prerelease -t node -t browser --preid rc --dist-tag next
    ```
  - [x] Run tests of the following projects with the new release:
    - [x] [js-ipfs](https://github.com/ipfs/js-ipfs)
- Documentation
  - [x] Ensure that README.md is up to date
  - [x] Ensure that all the examples run
  - [x] Ensure that [libp2p/docs](https://github.com/libp2p/docs) is updated
- Communication
  - [x] Create the release issue
  - [x] Take a snapshot between of everyone that has contributed to this release (including its subdeps in IPFS, libp2p, IPLD and multiformats) using [`name-your-contributors`](https://www.npmjs.com/package/name-your-contributors). Generate a nice markdown list with [this script](https://gist.github.com/jacobheun/d2ff479ca991733c13cdcf688a1317e5)
  - [ ] Announcements (both pre-release and post-release)
    - [x] Twitter
    - [ ] IRC
    - [x] Reddit
    - [x] [discuss.libp2p.io](https://discuss.libp2p.io/c/news)
  - [ ] Blog post
  - [x] Copy release notes to the [GitHub Release description](https://github.com/libp2p/js-libp2p/releases)

# ❤️ Huge thank you to everyone that made this release possible

In alphabetical order, here are all the humans that contributed to the release:

* [3xtr4t3rr3str14l](https://github.com/3xtr4t3rr3str14l) (1 review)
* [a1300](https://github.com/a1300) (3 PRs, 10 issues, 11 comments)
* [acolytec3](https://github.com/acolytec3) (1 PR)
* [Adam Uhlíř](https://github.com/AuHau) (1 issue, 4 comments)
* [Alex Potsides](https://github.com/achingbrain) (8 PRs, 12 reviews, 5 comments)
* [anders](https://github.com/tabcat) (1 issue, 4 comments)
* [Andrey Petrov](https://github.com/shazow) (1 PR)
* [Belma Gutlic](https://github.com/morrigan) (4 reviews)
* [Cayman](https://github.com/wemeetagain) (3 PRs, 1 issue, 6 reviews, 6 comments)
* [Chris Hafey](https://github.com/chafey) (2 issues, 1 comment)
* [Cindy Wu](https://github.com/cindywu) (1 PR)
* [CLAassistant](https://github.com/CLAassistant) (1 comment)
* [Codecov](https://github.com/codecov-io) (2 comments)
* [Codecov Comments Bot](https://github.com/codecov-commenter) (5 comments)
* [Collin Schroeder](https://github.com/ubernaut) (1 issue, 1 comment)
* [Daniel Maricic](https://github.com/woss) (1 issue, 6 comments)
* [Daniel Pendergast](https://github.com/DanPen) (1 PR)
* [David Dias](https://github.com/daviddias) (1 comment)
* [dependabot](undefined) (4 PRs)
* [dependabot-preview](undefined) (55 PRs, 46 comments)
* [Ethan Lam](https://github.com/EthanTheMaster) (1 PR, 1 comment)
* [George Shammas](https://github.com/georgyo) (1 issue)
* [Hubertus Hohl](https://github.com/ffa500) (1 comment)
* [Hugo Dias](https://github.com/hugomrdias) (7 PRs, 15 reviews, 2 comments)
* [imestin](https://github.com/imestin) (3 comments)
* [Irakli Gozalishvili](https://github.com/Gozala) (1 PR, 3 issues, 15 reviews, 6 comments)
* [Jacob Friedman](https://github.com/jacobfriedman) (1 PR, 7 comments)
* [Jacob Heun](https://github.com/jacobheun) (6 PRs, 5 issues, 97 reviews, 48 comments)
* [Jon](https://github.com/Schwartz10) (1 issue, 1 comment)
* [Jonathan Lorimer](https://github.com/JonathanLorimer) (1 comment)
* [Josh Field](https://github.com/HexaField) (5 PRs, 5 issues, 13 comments)
* [kottackalsulvin](https://github.com/kottackalsulvin) (3 issues, 10 comments)
* [Lion - dapplion](https://github.com/dapplion) (5 reviews)
* [Marcin Rataj](https://github.com/lidel) (1 PR, 1 comment)
* [Marin Petrunić](https://github.com/mpetrunic) (6 PRs, 4 reviews, 3 comments)
* [Mark Gaiser](https://github.com/markg85) (2 issues, 9 comments)
* [mcclure](https://github.com/mcclure) (3 issues, 3 comments)
* [mh-cbon](https://github.com/mh-cbon) (2 issues, 1 comment)
* [Michael Burns](https://github.com/mburns) (2 PRs, 5 comments)
* [Mike Goelzer](https://github.com/mgoelzer) (1 issue)
* [olivier nerot](https://github.com/on-meetsys) (1 comment)
* [Orie Steele](https://github.com/OR13) (1 issue, 5 comments)
* [Rod Vagg](https://github.com/rvagg) (1 comment)
* [Samlior](https://github.com/samlior) (1 PR)
* [Smite Chow](https://github.com/lovemyliwu) (3 PRs, 2 reviews, 6 comments)
* [stale](undefined) (14 comments)
* [StationedInTheField](https://github.com/StationedInTheField) (1 issue, 4 comments)
* [tuyennhv](https://github.com/tuyennhv) (3 PRs, 4 reviews, 1 comment)
* [Vasco Santos](https://github.com/vasco-santos) (60 PRs, 14 issues, 165 reviews, 124 comments)
* [Volker Mische](https://github.com/vmx) (1 review, 6 comments)
* [Xplorer123](https://github.com/Xplorer123) (1 issue)
* [Максим Ильин](https://github.com/negamaxi) (1 comment)

# 🙌🏽 Want to contribute?

Would you like to contribute to the libp2p project and don't know how? Well, there are a few places you can get started:

- Check the issues with the `help wanted` label in the [libp2p repo](https://github.com/libp2p/js-libp2p/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)
- Join an IPFS All Hands, introduce yourself and let us know where you would like to contribute - https://github.com/ipfs/team-mgmt#all-hands-call
- Hack with IPFS and show us what you made! The All Hands call is also the perfect venue for demos, join in and show us what you built
- Join the discussion at http://discuss.libp2p.io/ and help users finding their answers.
- Join the [⚡️libp2p Weekly Sync 🙌🏽](https://github.com/libp2p/team-mgmt/issues/16) and be part of the Sprint action!

# ⁉️ Do you have questions?

The best place to ask your questions about libp2p, how it works and what you can do with it is at [discuss.libp2p.io](https://discuss.libp2p.io). We are also available at the #libp2p channel on Freenode.

**Comment by jacobheun** [comment]
Related to connection gating: https://github.com/libp2p/js-libp2p/issues/175
