### ISSUE TITLE
[Meta] Improving libp2p discoverability and connectivity

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#703]
This is a Meta issue for tracking several sub systems involved in improving discoverability and connectivity in js-libp2p. This list is not an exhaustive and will evolve over time.

## Connectivity
- [ ] [AutoRelay support](https://github.com/libp2p/js-libp2p/issues/699)
- [ ] AutoNAT to determine dialability

## Discoverability
- [ ] [Connect to closest peers](https://github.com/libp2p/js-libp2p/issues/704)
- [ ] Implement the DHT changes from go-ipfs 0.5 to improve performance
- [ ] Implement the [rendezvous protocol](https://github.com/libp2p/js-libp2p/issues/651)
- [X] Delegate routing

**Comment by wemeetagain** [comment]
closing as stale. most or all of these items have been implemented
